# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: []
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         max_age: 0
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#         skip_same_as_origin: true
#     paths:
#         '^/api/':
#             allow_origin: ['*']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
#             max_age: 3600
#         '^/':
#             origin_regex: true
#             allow_origin: ['^http://localhost:[0-9]+']
#             allow_headers: ['X-Custom-Auth']
#             allow_methods: ['POST', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
#             max_age: 3600
#             hosts: ['^api\.']

# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: ['*']
#         allow_headers: []
#         allow_methods: []
#         expose_headers: []
#         max_age: 0
#         hosts: []
#         origin_regex: false
#         forced_allow_origin_value: ~
#     paths:
#         '^/api/': # Замените на ваш путь API
#             allow_origin: ['*']
#             allow_headers: ['*']
#             allow_methods: ['POST', 'PATCH', 'GET', 'DELETE', 'OPTIONS']

# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null

nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['*']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Access-Control-Request-Headers', 'Access-Control-Request-Method', 'Content-Type', 'Authorization', 'X-Custom-Auth']
    max_age: 3600
  paths:
    '^/': ~